learning_log/learn_log/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry')

]

learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learn_log.urls')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
]

learning_log/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register')
]

learning_log/learn_log/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries' # В админке будет выглядить Entries вместо Entrys

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + "..." # описание топика в админке будет срезано на 50 символов
        else:
            return self.text

learning_log/user/models.py
from django.db import models

# Create your models here.

learning_log/learn_log/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learn_log/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    context = {
        'title': 'Learning Log'
    }
    return render(request, 'index.html', context)

 # закрыть доступ к топикам если пользователь не зареган
@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {
        'title': 'Темы',
        'topics': topics,
    }
    return render(request, 'topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'title': topic,
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST': #если данные не были отправлены, то создать пустую форму
        form = TopicForm()
    else: # иначе обработать данные введенные пользователем
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('topics'))
    context = {
        'form': form
    }
    return render(request, 'new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    
    check_topic_owner(topic.owner, request.user)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid:
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('topic', args=[topic_id]))
    context = {
        'topic': topic,
        'form': form,
    }
    return render(request, 'new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('topic', args=[topic.id])) # возвращяем пользователя на отредактированную запись
    context = {
        'title': 'Редактирование записи',
        'entry': entry,
        'topic': topic,
        'form': form,
    }
    return render(request, 'edit_entry.html', context)


def check_topic_owner(topic_owner, request_user):
    if topic_owner != request_user:
        raise Http404

learning_log/user/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

    if form.is_valid():
        new_user = form.save()
        authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('index'))
    context = {
        'title': 'Регистрация',
        'form': form,}
    return render(request, 'register.html', context)

    

learning_log/learn_log/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Статическая навигационная панель -->
	 <nav class="navbar navbar-default navbar-static-top">
 <div class="container">

 <div class="navbar-header">
	 <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
    </button>
    	 <a class="navbar-brand" href="{% url 'index' %}">Learning Log</a>
     </div>
    
    	 <div id="navbar" class="navbar-collapse collapse">
    	 <ul class="nav navbar-nav">
    	 <li><a href="{% url 'topics' %}">Темы</a></li>
     </ul>
    
    	 <ul class="nav navbar-nav navbar-right">
     {% if user.is_authenticated %}

        <li><a>Здравствуйте, {{ user.username }}</a></li>
        <li><a href="{% url 'user:logout' %}">Выйти</a></li>
     {% else %}
        <li><a href="{% url 'user:register' %}">Регистрация</a></li>
        <li><a href="{% url 'user:login' %}">Войти</a></li>
     {% endif %}
    	 </ul>
     </div><!--/.nav-collapse -->
     </div>
     </nav>
     <div class="container">
        <div class="page-header">
       	 {% block header %}

         {% endblock header %}
        </div>
        <div>
       	 {% block content %}

         {% endblock content %}
        </div>
        </div>
        <style>
          
         .wrapper{
             min-height: 100%;
             display: flex;
             flex-direction: column;
         }
         
         .container{
             background: #F8F8F8;
         }
         .footer__title{
             height: 80px;
             text-align: center;
             padding-top: 30px; 
             color: #777777;
         }
         </style>
         
         <body>
             <div class="wrapper">
                 <header class="header"></header>
                 <main class="main"></main>
                 <footer class="footer">
                     <div class="container">
                         <h2 class="footer__title">
                             Powered by scri0x
                         </h2>
                     </div>
             </div>
             </footer>
</body>
</html>

learning_log/learn_log/templates/edit_entry.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>
    Редактирование записи: <a href="{% url 'topic' topic.id %}">{{topic}}</a>
</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'edit_entry' entry.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name='submit'>Применить изменения</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/learn_log/templates/index.html
{% extends 'base.html' %}

{% block header %}
<div class="jumbotron">
    <h1>Отслеживайте свое обучение.</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'user:register' %}">Зарегистрируйте учетную запись</a> чтобы вести
    свой собственный журнал обучения, и перечислите темы, которые вы изучаете.
</h2>
<h2>
    Всякий раз, когда вы узнаете что-то новое по теме, делайте запись, резюмируя то, что вы узнали.
</h2>

{% endblock content %}

learning_log/learn_log/templates/new_entry.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>
  Добавить новую запись в: <a href="{% url 'topic' topic.id %}">{{ topic }}</a>
</h2>
{% endblock header %}
{% block content %}

<form method='post' class="form">
 {% csrf_token %}
 {% bootstrap_form form %}
 {% buttons %}
 <button name='submit'>Добавить запись</button>
 {% endbuttons %}
</form>
{% endblock content %}

learning_log/learn_log/templates/new_topic.html
{% extends 'base.html' %}
{% block content %}

  <p> Создание новой темы: </p>
  <form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Добавить тему</button>
  </form>

{% endblock content %}

learning_log/learn_log/templates/topic.html
{% extends 'base.html' %}

{% block header %}
 <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

  <p>Тема под названием: {{ topic }}</p>
  <p>
    <a href="{% url 'new_entry' topic.id %}">Добавить новую запись</a>
    </p>
  <ul>
    {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
      	 <small>
           <a href="{% url 'edit_entry' entry.id %}">Редактировать запись</a>

          </small>
       </h3>
     </div>
	    <div class="panel-body">
      {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
{% empty %}
  В этой теме пока нет записей.
{% endfor %}


{% endblock content %}

learning_log/learn_log/templates/topics.html
{% extends 'base.html' %}
{% block header %}
 <h1>Темы</h1>
{% endblock header %}

{% block content %}
<title>{{title}}</title>
<ul>
  {% for topic in topics %}
  <li>
  	 <h3>
      <a href="{% url 'topic' topic.id %}">{{ topic }}</a>
     </h3>
  </li>
    {% empty %}
    <li>Темы еще не добавлены.</li>
    {% endfor %}
  </ul>
  <h3><a href="{% url 'new_topic' %}">Добавить новую тему</h3>

  
{% endblock content %}

learning_log/user/templates/login.html
{% extends './base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>
    Войдите в свою учетную запись
</h2>
{% endblock header %}
{% block content %}


<form method="post" action="{% url 'user:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit">Войти</button>
    {% endbuttons %}
    
    <input type="hidden" name="text" value=" {% url 'index' %} ">
</form>
{% endblock content %}

learning_log/user/templates/register.html
{% extends './base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>
    Регистрация
</h2>
{% endblock header %}
{% block content %}
    <title>{{ title }}</title>
    <form action="{% url 'user:register' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit">Зарегистрироваться</button>
        {% endbuttons %}
        <input type="hidden" name="text" value={% url 'index' %}>
    </form>
{% endblock content %}